version: '3.8'
services:
  php:
    build: .
    container_name: lab7_php
    volumes:
      - ./www:/var/www/html
    depends_on:
      - rabbitmq
      - kafka

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lab7_rabbit
    ports:
      - "5672:5672"
      - "15672:15672" 

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: lab7_zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: lab7_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  web:
    image: nginx:1.27-alpine
    container_name: lab7_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
